spring:
  application:
    name: ticketing-service
  datasource:
    url: jdbc:postgresql://localhost:5434/ticketing_db
    username: ticketinguser
    password: ticketingpass
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: ticketing-service
      auto-offset-reset: earliest
      max-poll-records: 10
    listener:
      poll-timeout: 3000
      type: batch
      ack-mode: manual

server:
  port: 8004

logging:
  level:
    "[org.springframework.web]": INFO
    "[org.hibernate]": WARN
